coverage:
  range: 80..100  # Slightly lower minimum since embedded edge cases can be hard to test
  round: down
  precision: 1
  status:
    project:
      default:
        threshold: 1%
    # Add patch status to ensure new code maintains coverage
    patch:
      default:
        target: 85%
        threshold: 5%

# Ignore test files and example code
ignore:
  - "tests"
  - "examples"
  - "benches"

# Configure component-specific targets
component:
  status:
    project:
      blocking:
        target: 85%
        paths: ["src/blocking.rs"]
      nonblocking:
        target: 85%
        paths: ["src/nonblocking.rs"]

# Make comments less noisy but informative
comment:
  layout: "files"
  require_changes: true
  show_carryforward_flags: true
  