version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    ignore:
      # Only ignore patch updates for dev-dependencies
      - dependency-name: "criterion"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "tokio"
        update-types: ["version-update:semver-patch"]
      - dependency-name: "hex-literal"
        update-types: ["version-update:semver-patch"]
    groups:
      # Group embedded-io updates together to ensure compatibility
      embedded-io:
        patterns:
          - "embedded-io*"
      # Group dev dependencies updates
      dev-dependencies:
        patterns:
          - "criterion"
          - "tokio"
          - "hex-literal"
