[package]
name = "sbus-rs"
version = "0.1.0"
edition = "2021"

# TODO: Check if this is the correct MSRV
rust-version = "1.70"

[features]
default = ["blocking"]

std = []
blocking = ["dep:embedded-io", "embedded-io-adapters/std"]
async = ["dep:embedded-io-async", "embedded-io-adapters/tokio-1"]

[dependencies]
heapless = { version = "0.8" }
embedded-io = { version = "0.6", optional = true }
embedded-io-async = { version = "0.6", optional = true }

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
embedded-io-adapters = { version = "0.6" }
criterion = "0.5"
hex-literal = "0.4"
